πρόγραμμα τεστ_teams4
    δήλωση age,creditScore,income

    αρχή_προγράμματος
    διάβασε age ;
    διάβασε creditScore;
    διάβασε income ;

    εάν [age >= 18 και age <= 65] και
        [[income >= 2000 και creditScore >= 650] ή
         [income >= 5000] ή
         [creditScore >= 700 και income >= 1500]] τότε
        γράψε 1
    αλλιώς
        γράψε 0
    εάν_τέλος

    τέλος_προγράμματος